### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by errant-info** [Bannerets/keybase-export#18]
Having the following issue with the latest master build (wasn't present in b2a9501022ee516a8377aa7b3abad51dc86d73da)
```
./bin/keybase-export config.json                                     [2023-04-11 13:28:45]
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'fs/promises'
Require stack:
- /Users/ndawsonfresh/dev/keybase-export/dist/index.js
- /Users/ndawsonfresh/dev/keybase-export/bin/keybase-export
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ndawsonfresh/dev/keybase-export/dist/index.js:35:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ndawsonfresh/dev/keybase-export/dist/index.js',
    '/Users/ndawsonfresh/dev/keybase-export/bin/keybase-export'
  ]
}
```

**Comment by eilvelia** [comment]
You need to update Node.js to the latest version. I think at least v10.0.0 is required now.

**Comment by errant-info** [comment]
Ah yep, was a local env issue - had the latest node installed but it wasn't active (nvm vs brew mismatch)
